In [26]:
import pandas as pd
import numpy as np
import statistics as st
import matplotlib.pyplot as plt
df=pd.read_csv('lab1_pr.csv')
print(df.to_string())


  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198


In [15]:
data_A=['Candies (#)','Mangoes (Kg)','Milk Packets (#)']
data_B=['Payment (Rs)']

In [16]:
matrix_A=df[data_A].values
matrix_B=df[data_B].values

In [17]:
#to print the matrix A
print(matrix_A)


[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]


In [18]:
#to print the matrix B
print(matrix_B)

[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]


In [19]:
#to find the dimensionality of the matrix_A
dimensionality = len(data_A)

print("Dimensionality of the matrix_A is:", dimensionality)
# to find the dimensionality of the matrix_B
dimensionality =len(data_B)

print("Dimensionality of the matrix_B is:", dimensionality)

Dimensionality of the matrix_A is: 3
Dimensionality of the matrix_B is: 1


In [20]:
#What is the dimensionality of the vector space for this data?
dim=len(data_A)+len(data_B)
print(" dimensionality of the vector space for this data is:",dim)

 dimensionality of the vector space for this data is: 4


In [21]:
num_vectors =len(df)
print("Number of vectors in the vector space:", num_vectors)

Number of vectors in the vector space: 10


In [22]:
#the rank of the matrix A is
rank = np.linalg.matrix_rank(matrix_A)

print("Rank of the matrix A is :", rank)

Rank of the matrix A is : 3


In [23]:
'''The code first creates a matrix of the given data, where each row represents a customer and each column represents a product. 
The Pseudo-Inverse of the matrix is then calculated using the numpy.linalg.pinv() function. 
Finally, the cost of each product is obtained by multiplying the Pseudo-Inverse with the Payment column. 
The resulting cost of each product is printed as output.
Overall, the code uses the Pseudo-Inverse method to solve a system of linear equations and find the cost of each product available for sale.'''
# Calculate the pseudo-inverse of A
A_pseudo_inv = np.linalg.pinv(matrix_A)

# Calculate the cost vector x
x = np.dot(A_pseudo_inv, matrix_B)

# Extract the individual costs
C_candies, C_mangoes, C_milk_packets = x

# Print the results
print("Cost of one candy:", C_candies)
print("Cost of one kilogram of mangoes:", C_mangoes)
print("Cost of one milk packet:", C_milk_packets)

Cost of one candy: [1.]
Cost of one kilogram of mangoes: [55.]
Cost of one milk packet: [18.]


In [24]:
#to find the dimension of the data frame
print("Dimension of the data fram: ",df.shape)

Dimension of the data fram:  (10, 5)


In [25]:
#A3. Mark all customers (in “Purchase Data” table) with payments above Rs. 200 as RICH and others 
#as POOR. Develop a classifier model to categorize customers into RICH or POOR class based on 
#purchase behavior'''
df['Purchase Category'] = df['Payment (Rs)'].apply(lambda x: 'Rich' if x > 200 else 'Poor')
print(df.head())


  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   

  Purchase Category  
0              Rich  
1              Rich  
2              Rich  
3              Poor  
4              Rich  
